[package]
name = "unirun-plugin-applications"
version = "0.2.2-alpha"
edition = "2021"

[dependencies]
unirun-if = { path = "../../unirun-interface", package = "unirun-interface" }
glib = { workspace = true }
gio = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
